In [45]:
import pandas as pd
import numpy as np

data = {
    '이름' : ['유재석', '박명수', '정준하', '노홍철', '정형돈', '하하'],
    '지역' : ['서울', '부산', '부산', '서울', '서울', '서울'],
    '나이' : [19, 23, 20, 25, 18, 21],
    '국어점수' : [86, 90, 80, 65, 50, 60],
    '수학점수' : [86, 100, 66, 70, 40, 80],
    '코딩' : ['Python', 'Java', np.nan, 'Javascript', 'PYTHON', np.nan]
}

df = pd.DataFrame(data, index=['1번', '2번', '3번', '4번', '5번', '6번'])
print(df)
# df.info()

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  서울  19    86    86      Python
2번  박명수  부산  23    90   100        Java
3번  정준하  부산  20    80    66         NaN
4번  노홍철  서울  25    65    70  Javascript
5번  정형돈  서울  18    50    40      PYTHON
6번   하하  서울  21    60    80         NaN

In [46]:
# 컬럼 내용 수정
df["지역"].replace({"서울":"경기","부산":"대구"},inplace=True)
df

/tmp/ipykernel_1570/564687192.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["지역"].replace({"서울":"경기","부산":"대구"},inplace=True)

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  경기  19    86    86      Python
2번  박명수  대구  23    90   100        Java
3번  정준하  대구  20    80    66         NaN
4번  노홍철  경기  25    65    70  Javascript
5번  정형돈  경기  18    50    40      PYTHON
6번   하하  경기  21    60    80         NaN

In [47]:
#대소문자가 섞여있는 '코딩' 컬럼을 모두 소문자로 바꾸고 싶음
#해당 열이 문자열(string)일 경우, 문자열 관련 메서드를 적용할 수 있게 해줌
df['코딩'] = df['코딩'].str.lower()
df

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  경기  19    86    86      python
2번  박명수  대구  23    90   100        java
3번  정준하  대구  20    80    66         NaN
4번  노홍철  경기  25    65    70  javascript
5번  정형돈  경기  18    50    40      python
6번   하하  경기  21    60    80         NaN

In [48]:
#대소문자가 섞여있는 '코딩' 컬럼을 모두 대문자로 바꾸고 싶음

df['코딩'] = df['코딩'].str.upper()
df

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  경기  19    86    86      PYTHON
2번  박명수  대구  23    90   100        JAVA
3번  정준하  대구  20    80    66         NaN
4번  노홍철  경기  25    65    70  JAVASCRIPT
5번  정형돈  경기  18    50    40      PYTHON
6번   하하  경기  21    60    80         NaN

In [49]:
# 국어 점수 5점 올리기

df['국어점수'] = df['국어점수'] + 5
df

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  경기  19    91    86      PYTHON
2번  박명수  대구  23    95   100        JAVA
3번  정준하  대구  20    85    66         NaN
4번  노홍철  경기  25    70    70  JAVASCRIPT
5번  정형돈  경기  18    55    40      PYTHON
6번   하하  경기  21    65    80         NaN

In [50]:
# 컬럼 추가
# 없으면 추가, 있으면 해당 값 업데이트

#점수종합 컬럼에 국어점수 + 수학점수가 들어 가도록 하시오.
df['점수총합'] = df['국어점수'] + df['수학점수']
print(df)

     이름  지역  나이  국어점수  수학점수          코딩  점수총합
1번  유재석  경기  19    91    86      PYTHON   177
2번  박명수  대구  23    95   100        JAVA   195
3번  정준하  대구  20    85    66         NaN   151
4번  노홍철  경기  25    70    70  JAVASCRIPT   140
5번  정형돈  경기  18    55    40      PYTHON    95
6번   하하  경기  21    65    80         NaN   145

In [51]:
# 결과 컬럼 생성, 불합격으로 전부 초기화 하시오.

df["결과"] = "불합격"
df

     이름  지역  나이  국어점수  수학점수          코딩  점수총합   결과
1번  유재석  경기  19    91    86      PYTHON   177  불합격
2번  박명수  대구  23    95   100        JAVA   195  불합격
3번  정준하  대구  20    85    66         NaN   151  불합격
4번  노홍철  경기  25    70    70  JAVASCRIPT   140  불합격
5번  정형돈  경기  18    55    40      PYTHON    95  불합격
6번   하하  경기  21    65    80         NaN   145  불합격

In [52]:
# 점수총합이 160 점을 넘으면 , 결과 컬럼에 '합격'
print(df[ df['점수총합'] >160 ])
df.loc[ df['점수총합'] > 160 , '결과'] = "합격"
df

     이름  지역  나이  국어점수  수학점수      코딩  점수총합   결과
1번  유재석  경기  19    91    86  PYTHON   177  불합격
2번  박명수  대구  23    95   100    JAVA   195  불합격

     이름  지역  나이  국어점수  수학점수          코딩  점수총합   결과
1번  유재석  경기  19    91    86      PYTHON   177   합격
2번  박명수  대구  23    95   100        JAVA   195   합격
3번  정준하  대구  20    85    66         NaN   151  불합격
4번  노홍철  경기  25    70    70  JAVASCRIPT   140  불합격
5번  정형돈  경기  18    55    40      PYTHON    95  불합격
6번   하하  경기  21    65    80         NaN   145  불합격

In [53]:
# 컬럼 삭제
df.drop(columns=['점수총합','결과'],inplace=True)
print(df)

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  경기  19    91    86      PYTHON
2번  박명수  대구  23    95   100        JAVA
3번  정준하  대구  20    85    66         NaN
4번  노홍철  경기  25    70    70  JAVASCRIPT
5번  정형돈  경기  18    55    40      PYTHON
6번   하하  경기  21    65    80         NaN

In [54]:
# 행단위 CRUD

# 행추가
df.loc["7번"] = ["길",  "부산" , 22  ,90  ,  80 ,"java"  ]
df

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  경기  19    91    86      PYTHON
2번  박명수  대구  23    95   100        JAVA
3번  정준하  대구  20    85    66         NaN
4번  노홍철  경기  25    70    70  JAVASCRIPT
5번  정형돈  경기  18    55    40      PYTHON
6번   하하  경기  21    65    80         NaN
7번    길  부산  22    90    80        java

In [ ]:
# 셀 수정
df.loc['4번','국어점수'] = 90
df

In [56]:
# 두개 이상의 행의 값을 변경 할때
df.loc['4번',["지역","코딩"]] = ["대구","python"]
df

     이름  지역  나이  국어점수  수학점수      코딩
1번  유재석  경기  19    91    86  PYTHON
2번  박명수  대구  23    95   100    JAVA
3번  정준하  대구  20    85    66     NaN
4번  노홍철  대구  25    90    70  python
5번  정형돈  경기  18    55    40  PYTHON
6번   하하  경기  21    65    80     NaN
7번    길  부산  22    90    80    java

In [57]:
# 1번 유재석 나이 20로,  지역을 광주로 바꾸시오.
df.loc['1번',["나이","지역"]] = [20,"광주"]
df

     이름  지역  나이  국어점수  수학점수      코딩
1번  유재석  광주  20    91    86  PYTHON
2번  박명수  대구  23    95   100    JAVA
3번  정준하  대구  20    85    66     NaN
4번  노홍철  대구  25    90    70  python
5번  정형돈  경기  18    55    40  PYTHON
6번   하하  경기  21    65    80     NaN
7번    길  부산  22    90    80    java