In [11]:
import pandas as pd
import numpy as np

data = {
    '이름' : ['유재석', '박명수', '정준하', '노홍철', '정형돈', '하하'],
    '지역' : ['서울', '부산', '부산', '서울', '서울', '서울'],
    '나이' : [19, 23, 20, 25, 18, 21],
    '국어점수' : [86, 90, 80, 65, 50, 60],
    '수학점수' : [86, 100, 66, 70, 40, 80],
    '코딩' : ['Python', 'Java', np.nan, 'Javascript', 'PYTHON', np.nan],
    '전공' : ['문과', '이과', '이과', '이과', '문과', '문과'], 
}

df = pd.DataFrame(data, index=['1번', '2번', '3번', '4번', '5번', '6번'])
#print(df)

#결측치 체크
#df.info()
df.isnull().sum()

이름      0
지역      0
나이      0
국어점수    0
수학점수    0
코딩      2
전공      0
dtype: int64

In [12]:
# 데이터프레임의 '지역' 컬럼 내 데이터들을 모두 결측치로 지정
df['지역'] =  np.nan
print(df)

     이름  지역  나이  국어점수  수학점수          코딩  전공
1번  유재석 NaN  19    86    86      Python  문과
2번  박명수 NaN  23    90   100        Java  이과
3번  정준하 NaN  20    80    66         NaN  이과
4번  노홍철 NaN  25    65    70  Javascript  이과
5번  정형돈 NaN  18    50    40      PYTHON  문과
6번   하하 NaN  21    60    80         NaN  문과

In [14]:
# fillna 를 통해 결측치 값을 바꿈
# df.fillna('없음', inplace=True)
# print(df)

#특정열지정하여 처리하기
df["지역"].fillna('없음', inplace=True)
print(df)

# 삭제
# NaN 을 가진 모든 행 삭제
df.dropna(inplace=True)
df

     이름  지역  나이  국어점수  수학점수          코딩  전공
1번  유재석  없음  19    86    86      Python  문과
2번  박명수  없음  23    90   100        Java  이과
3번  정준하  없음  20    80    66         NaN  이과
4번  노홍철  없음  25    65    70  Javascript  이과
5번  정형돈  없음  18    50    40      PYTHON  문과
6번   하하  없음  21    60    80         NaN  문과

     이름  지역  나이  국어점수  수학점수          코딩  전공
1번  유재석  없음  19    86    86      Python  문과
2번  박명수  없음  23    90   100        Java  이과
4번  노홍철  없음  25    65    70  Javascript  이과
5번  정형돈  없음  18    50    40      PYTHON  문과

In [ ]:
# 결측치 처리(대체) 방법

# 1. 평균
# 2. 최빈값 = 
# 3. 해당 컬럼 삭제
# 4. 최대 최소값
# 6. 중앙값
# 7. 이전값으로 채우기 또는 다음값으로 채우기
100
NaN
130