In [37]:
import seaborn as sns
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    classification_report
)

In [38]:
# 1. 데이터 수집
titanic = sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [39]:
# 2. 필요한 컬럼 선택
df = titanic[["survived","age","fare","sex","pclass"]].copy()
df

     survived   age     fare     sex  pclass
0           0  22.0   7.2500    male       3
1           1  38.0  71.2833  female       1
2           1  26.0   7.9250  female       3
3           1  35.0  53.1000  female       1
4           0  35.0   8.0500    male       3
..        ...   ...      ...     ...     ...
886         0  27.0  13.0000    male       2
887         1  19.0  30.0000  female       1
888         0   NaN  23.4500  female       3
889         1  26.0  30.0000    male       1
890         0  32.0   7.7500    male       3

[891 rows x 5 columns]

In [40]:
# 3. 결측치 처리
# df.info()
df["age"] = df["age"].fillna(df["age"].median())
df

     survived   age     fare     sex  pclass
0           0  22.0   7.2500    male       3
1           1  38.0  71.2833  female       1
2           1  26.0   7.9250  female       3
3           1  35.0  53.1000  female       1
4           0  35.0   8.0500    male       3
..        ...   ...      ...     ...     ...
886         0  27.0  13.0000    male       2
887         1  19.0  30.0000  female       1
888         0  28.0  23.4500  female       3
889         1  26.0  30.0000    male       1
890         0  32.0   7.7500    male       3

[891 rows x 5 columns]

In [ ]:
# 4. 원 핫 인코딩
df = pd.get_dummies(df,columns=["sex"],drop_first=True)
df

     survived   age     fare  pclass  sex_male
0           0  22.0   7.2500       3      True
1           1  38.0  71.2833       1     False
2           1  26.0   7.9250       3     False
3           1  35.0  53.1000       1     False
4           0  35.0   8.0500       3      True
..        ...   ...      ...     ...       ...
886         0  27.0  13.0000       2      True
887         1  19.0  30.0000       1     False
888         0  28.0  23.4500       3     False
889         1  26.0  30.0000       1      True
890         0  32.0   7.7500       3      True

[891 rows x 5 columns]

In [ ]:
# 5. x,y 분리 (독립변수,종속변수)

x = df[["age", "fare", "pclass", "sex_male"]]
y = df["survived"]